config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get "/series", to: "series#index", as: 'series'
  get "/series/new", to: "series#new", as: 'new_serie'
  post "/series", to: "series#create"
  get "/series/:id", to: "series#show", as: 'serie'

  get "/movies", to: "movies#index", as: 'movies'
  get "/movies/new", to: "movies#new", as: 'new_movie'
  post "/movies", to: "movies#create"
  get "/movies/:id", to: "movies#show", as: 'movie'
  
  get "/documentary_films", to: "documentary_films#index", as: "documentary_films"
  get "/documentary_films/new", to: "documentary_films#new", as: "new_documentary_film"
  post "documentary_films", to: "documentary_films#create"
  get "/documentary_films/:id", to: "documentary_films#show", as: "documentary_film"

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  # lista todas los documentales
  def index
    @documentary_films = DocumentaryFilm.all
  end

  # muestra un documental
  def show
    @documentary_film = DocumentaryFilm.find(params[:id])
  end

  # instancia un nuevo documental
  def new
    @documentary_film = DocumentaryFilm.new
  end

  # crea un nuevo documental
  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)

    if @documentary_film.save
      redirect_to documentary_films_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  private

  # metodo para definir los parametros que se van a permitir
  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # lista todas las movies
  def index
    @movies = Movie.all
  end

  # muestra una movie
  def show
    @movie = Movie.find(params[:id])
  end

  # instancia una nueva movie
  def new
    @movie = Movie.new
  end

  # crea una nueva movie
  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  private

  # metodo para definir los parametros que se van a permitir
  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  # lista todas las series
  def index
    @series = Serie.all
  end

  # muestra una serie
  def show
    @serie = Serie.find(params[:id])
  end

  # instancia una nueva serie
  def new
    @serie = Serie.new
  end

  # crea una nueva serie
  def create
    @serie = Serie.new(serie_params)

    if @serie.save
      redirect_to series_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  private

  # metodo para definir los parametros que se van a permitir
  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<h1>documentaryFilms#create</h1>

app/views/documentary_films/index.html.erb
<h1>Documentales</h1>

<p>Listado de Documentales</p>

<%= link_to 'Nuevo documental', new_documentary_film_path, class: "btn btn-warning my-1" %>

<table class="table table-hover">
  <thead class="table-dark"> 
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Sinopsis</th>
      <th scope="col">Director</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <% @documentary_films.each do |documentary_film| %>
    <tr>
      <td><%= documentary_film.name %></td>
      <td><%= documentary_film.synopsis %></td>
      <td><%= documentary_film.director %></td>
      <td>
        <%= link_to 'Ver', documentary_film_path(documentary_film), class: "btn btn-primary" %>
    </tr>
  <% end %>
</table>

app/views/documentary_films/new.html.erb
<h1>Agregar Documental</h1>

<%= form_with model: @documentary_film do |form| %>
<div class="col-4">
    <div>
        <%= form.label :name, "Nombre", class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div>
        <%= form.label :synopsys, "Sinopsis", class: "form-label" %>
        <%= form.text_field :synopsis, class: "form-control" %>
    </div>
    <div>
        <%= form.label :director, "Director", class: "form-label" %>
        <%= form.text_field :director, class: "form-control" %>
    </div>
    <div>
        <%= form.submit "Agregar", class: "btn btn-primary my-2" %>
    </div>
</div>
<% end %>

<div>
    <%= link_to 'Volver', documentary_films_path, class: "btn btn-primary my-2" %>
</div>

app/views/documentary_films/show.html.erb
<h1>Documental: <%= @documentary_film.name %></h1>
<ul>
    <li>Nombre: <%= @documentary_film.name %></li>
    <li>Sinopsis: <%= @documentary_film.synopsis %></li>
    <li>Director: <%= @documentary_film.director %></li>
</ul>

<%= link_to 'Volver', documentary_films_path, class: "btn btn-primary" %>

app/views/home/index.html.erb
<h1>Bienvenido al Desafio 3!</h1>
<p>Haz click en los links para comenzar:</p>

<%= link_to 'Peliculas', movies_path, class: "btn btn-warning"  %>
<%= link_to 'Series', series_path, class: "btn btn-warning"  %>
<%= link_to 'Documentales', documentary_films_path, class: "btn btn-warning" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Agrega bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movie#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h1>Peliculas</h1>

<p>Listado de Peliculas</p>

<%= link_to 'Nueva Pelicula', new_movie_path, class: "btn btn-warning my-1" %>

<table class="table table-hover">
  <thead class="table-dark"> 
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Sinopsis</th>
      <th scope="col">Director</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.name %></td>
      <td><%= movie.synopsis %></td>
      <td><%= movie.director %></td>
      <td>
        <%= link_to 'Ver', movie_path(movie), class: "btn btn-primary" %>
    </tr>
  <% end %>
</table>

app/views/movies/new.html.erb
<h1>Agregar Pelicula</h1>

<%= form_with model: @movie do |form| %>
<div class="col-4">
    <div>
        <%= form.label :name, "Nombre", class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div>
        <%= form.label :synopsys, "Sinopsis", class: "form-label" %>
        <%= form.text_field :synopsis, class: "form-control" %>
    </div>
    <div>
        <%= form.label :director, "Director", class: "form-label" %>
        <%= form.text_field :director, class: "form-control" %>
    </div>
    <div>
        <%= form.submit "Agregar", class: "btn btn-primary my-2" %>
    </div>
</div>
<% end %>

<div>
    <%= link_to 'Volver', movies_path, class: "btn btn-primary my-2" %>
</div>

app/views/movies/show.html.erb
<h1>Pelicula: <%= @movie.name %></h1>
<ul>
    <li>Nombre: <%= @movie.name %></li>
    <li>Sinopsis: <%= @movie.synopsis %></li>
    <li>Director: <%= @movie.director %></li>
</ul>

<%= link_to 'Volver', movies_path, class: "btn btn-primary" %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h1>Series</h1>

<p>Listado de Series</p>

<%= link_to 'Nueva Serie', new_serie_path, class: "btn btn-warning my-1" %>

<table class="table table-hover">
  <thead class="table-dark"> 
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Sinopsis</th>
      <th scope="col">Director</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <% @series.each do |serie| %>
    <tr>
      <td><%= serie.name %></td>
      <td><%= serie.synopsis %></td>
      <td><%= serie.director %></td>
      <td>
        <%= link_to 'Ver', serie_path(serie), class: "btn btn-primary" %>
    </tr>
  <% end %>
</table>

app/views/series/new.html.erb
<h1>Agregar Serie</h1>

<%= form_with model: @serie do |form| %>
<div class="col-4">
    <div>
        <%= form.label :name, "Nombre", class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div>
        <%= form.label :synopsys, "Sinopsis", class: "form-label" %>
        <%= form.text_field :synopsis, class: "form-control" %>
    </div>
    <div>
        <%= form.label :director, "Director", class: "form-label" %>
        <%= form.text_field :director, class: "form-control" %>
    </div>
    <div>
        <%= form.submit "Agregar", class: "btn btn-primary my-2" %>
    </div>
</div>
<% end %>

<div>
    <%= link_to 'Volver', series_path, class: "btn btn-primary my-2" %>
</div>

app/views/series/show.html.erb
<h1>Serie: <%= @serie.name %></h1>
<ul>
    <li>Nombre: <%= @serie.name %></li>
    <li>Sinopsis: <%= @serie.synopsis %></li>
    <li>Director: <%= @serie.director %></li>
</ul>

<%= link_to 'Volver', series_path, class: "btn btn-primary" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
  <div class="container-fluid" data-bs-theme="dark">
    <a class="navbar-brand" href="#">Desafio 3</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Peliculas", movies_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Series", series_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Documentales", documentary_films_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>